### ISSUE TITLE
Publishing to Maven Central

### ISSUE THREAD

**Issue by bripkens** [Skatteetaten/skatteprosessen-task#2]
Hey @raphw :),

your [advent of code post](https://www.javaadvent.com/2022/12/using-postgres-as-a-message-queue.html) and this lib came out as just the right time for us. Thank you!

I would love to give this one a try, but it does seem like it is not yet published to Maven Central. Is this correct? Any timeline when this might change? :)

Cheers,

Ben

**Comment by raphw** [comment]
Glad to hear!

I publish it under my own coordinates. (codes.rafael.task).

**Comment by bripkens** [comment]
Awesome, Thanks Rafael!
